"""auto migration

Revision ID: 1181698604ad
Revises: a5cbd3db4388
Create Date: 2025-10-13 14:30:44.582244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1181698604ad'
down_revision = 'a5cbd3db4388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.drop_column('feedback_type')

    # ### end Alembic commands ###
