"""auto migration

Revision ID: 129232779eed
Revises: 
Create Date: 2025-10-07 18:23:39.783963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129232779eed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('daily_read_hours', sa.Integer(), nullable=True),
    sa.Column('latest_exam_date', sa.Date(), nullable=True),
    sa.CheckConstraint('daily_read_hours >= 0 AND daily_read_hours <= 24', name='daily_read_hours_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reading_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('exam_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hours_per_day', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allocated_slot', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint('hours_per_day >= 0 AND hours_per_day <= 24', name='hours_per_day_range'),
    sa.CheckConstraint('level >= 1 AND level <= 10', name='level_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam_name', name='unique_user_exam')
    )
    op.create_table('daily_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('feedback_done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['reading_plans.id'], name='fk_dailyallocations_plan', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_allocations')
    op.drop_table('reading_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
