"""auto migration

Revision ID: 2e3abb6801a2
Revises: 7ceab4bdbff7
Create Date: 2025-10-09 15:58:53.518929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3abb6801a2'
down_revision = '7ceab4bdbff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_cleanup_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_cleanup_date')

    # ### end Alembic commands ###
