"""auto migration

Revision ID: 7ceab4bdbff7
Revises: bf319c6607c5
Create Date: 2025-10-07 23:17:58.674517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ceab4bdbff7'
down_revision = 'bf319c6607c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_dailyallocations_plan'), type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_daily_allocations_plan_id_reading_plans',  # ✅ ตั้งชื่อ constraint
            'reading_plans',
            ['plan_id'],
            ['id'],
            ondelete='SET NULL'
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_allocations_plan_id_reading_plans', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dailyallocations_plan'), 'reading_plans', ['plan_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
