"""auto migration

Revision ID: bf319c6607c5
Revises: 129232779eed
Create Date: 2025-10-07 19:43:26.005881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf319c6607c5'
down_revision = '129232779eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_name_snapshot', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_allocations', schema=None) as batch_op:
        batch_op.drop_column('exam_name_snapshot')

    # ### end Alembic commands ###
