"""auto migration

Revision ID: ecf7c01e98b9
Revises: 2e3abb6801a2
Create Date: 2025-10-11 06:00:28.566672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf7c01e98b9'
down_revision = '2e3abb6801a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    # ### end Alembic commands ###
